sudo: required

#language: go

services:
  - docker

cache:
  - apt

before_install:
  #- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t itsbalamurali/asha-asr .
  #- docker push itsbalamurali/heyasha

notifications:
  slack: heyasha:m1OwwwmiydtXPLKeUY1jwGzd
  email: false